name: Upload WAR
on:
  push:
  workflow_dispatch:
jobs:
  uploader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy results to the remote host over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "dev.war"
          target: "/opt/tomcat/latest/webapps/"
      - name: Change permissions to tomcat user
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: chown -R tomcat:tomcat /opt/tomcat
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
